SRCS=SettingDefinitionsXmlDeserializer.cpp \
     SettingDefinitionXmlDeserializer.cpp \

LIB=settings_serializers_definitions.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
